### ISSUE TITLE
Digispark Attiny85 and button

### ISSUE THREAD

**Issue by simonovich** [GyverLibs/GyverButton#1]
Загрузил пример из библиотеки, клики вроде ловит, но удержание (hold) - нет.
Импульсного удержание тоже не наблюдаю.

Вообще, очень сложно повестить кнопку именно на этот контроллер. Или вообще не работает, или работает через раз.
С внешним подтягивающим - очень плохо. С внутренним - уже лучше, но тоже плохо.
Игры с миллисс еще на пару пунктов улучшают ситуацию, но не решают проблему.
Мои любимые прерывания срабатывают хаотично и самопроизвольно. После эндцати часов тюнинга можно добиться срабатывания "через раз".

Что касается работы через "проверенную" библиотеку GyverButton - пока не понятно. Тоже нет четкой работы.

https://electrobattery.ru/wa-data/public/shop/products/23/22/2223/images/733/733.750x0.jpg

**Comment by GyverLibs** [comment]
Документацию на Дигиспарк изучали? Какие пины можно использовать, какие нельзя, в каких случаях?

**Comment by simonovich** [comment]
Изучали. И на практике не один скетч прошил, посмотрел как оно по отдельности, как оно вместе... Пару раз и себе в ногу выстрелил. Потом мозги в микруху программатором возвращал.
Ничего сложного мне от этой мелочи (digispark attiny85) не нужно, но есть нюансы. Потому как нужно мигать светодиодом и работать с serial. А работа с портом как бэ спорный вопрос у digispark.

Также я заметил, что есть более свежая либа encbutton, ниже код с ней:
```c
// Опциональные дефайн-настройки (показаны по умолчанию)
#define EB_DEB 100      // дебаунс кнопки, мс
#include <EncButton.h>
#include <DigiCDC.h>

#define LED_PIN 0
EncButton<EB_CALLBACK, 2> enc;       // просто кнопка <KEY>
bool flag = false;

void setup() {                
  // initialize the digital pin as an output.
  SerialUSB.begin(); 
  pinMode(LED_PIN,OUTPUT);
  enc.attach(CLICK_HANDLER, led_on_off);
  attachInterrupt(0, isr, CHANGE);  // D2
}

// the loop routine runs over and over again forever:
void loop() {
  enc.tick(); 
  //SerialUSB.delay(100);               // keep usb alive // can alos use SerialUSB.refresh();
}

void led_on_off() {
  SerialUSB.println("action");
  digitalWrite(LED_PIN,flag = !flag);
}

void isr() {
  enc.tickISR();  // в прерывании вызываем тик ISR
}
```

Даже что-то работает. Особенно когда дебаунс покрутил. Но работает через раз. Причем при открытом  мониторе порта стабильнее, чем при закрытом. Хотя по логике вещей этот момент ни на что влиять не должен.

**Comment by GyverLibs** [comment]
Плохо изучали значит. Библиотека работает идеально (специально сел проверил на Digi), но не ко всем пинам digispark можно подключать кнопки. Влияние serial здесь прямое, потому что сериал у дигиспарк - это программная эмуляция, отнимающая кучу ресурсов по сравнению с нативным uart как у обычных Arduino

**Comment by simonovich** [comment]
Хорошо. Значит, если я правильно подключу кнопку, то будет мне счастье. А за работу либы можно не переживать. Переберу пины еще раз. Спасибо.
